<?xml version="1.0" ?>
<TestCase>
    <TcExpectedResult>PASS</TcExpectedResult>
    <Discription>
Negative test: The DUT can retry GOTA update, after wifi reconnected during GOTA Update download failed
</Discription>
    <Domain>GOTA</Domain>
    <Phase>CORE</Phase>
    <b2bContinuousMode>True</b2bContinuousMode>
    <Type>FUNCTIONAL</Type>
    <UseCase>PY_UNIT</UseCase>
    <b2bIteration>1</b2bIteration>
    <Parameters>
        <Parameter>
            <Name>HpalmName</Name>
            <Value>check_gota_wifi_reconnect_during_gota.WifiReconnectDuringGOTA.testWifiReconnectDuringGOTA</Value>
        </Parameter>
        <Parameter>
            <Name>TEST_DATA_ROOT</Name>
            <Value>testplan/GOTA</Value>
        </Parameter>
        <Parameter>
            <Name>TEST_CASE</Name>
            <Value>tests.GOTA.GOTA.check_gota_wifi_reconnect_during_gota.WifiReconnectDuringGOTA.testWifiReconnectDuringGOTA</Value>
        </Parameter>
    </Parameters>
</TestCase>
